### ISSUE TITLE
environment querystring naming

### ISSUE THREAD

**Issue by wyvern8** [launchdarkly/ld-openapi#1]
https://github.com/launchdarkly/ld-openapi/blob/a85c272948cc2cd2e438089d43ea1930e801cad3/spec/parameters.yaml#L129

Is this meant to be 'env'? - it appears that is what the api actually expects.   when i generate a client with swagger-js and call functions that refer to this, the url used has querystring 'environmentKeyQuery' rather than 'env'  eg:

`https://app.launchdarkly.com/api/v2/flags/nab/demo-feature?environmentKeyQuery=dev`

so at the moment i need to translate this, ie:

```
        return Swagger({
            spec: json,
            usePromise: true,
            requestInterceptor: req => {
                req.headers.Authorization = API_TOKEN;

                // hack - fix incorrect qs mapping..
                req.url = req.url.replace('environmentKeyQuery', 'env');

                return req;
            }
        });
```

**Comment by atrakh** [comment]
Hi @wyvern8,

Thanks for bringing this to our attention. You're right- this was a typo on our end, and his been resolved in https://github.com/launchdarkly/ld-openapi/commit/b722851a060426744a8407d1eb6c5c5cf58d6046.

Thanks,
Arnold
