### ISSUE TITLE
published swagger.yaml mismatch

### ISSUE THREAD

**Issue by wyvern8** [launchdarkly/ld-openapi#2]
is this still the correct url for consumers?:

https://launchdarkly.github.io/ld-openapi/swagger.yaml

it is quite out of date, so i am compiling this locally and using output at the moment.

i also notice the swagger naming of tags in this repo no longer matches the published swagger file.  eg. 'flags' has become 'Feature flags'.   this means that the generated client from swagger-js results in a different interface for api calls - breaking contract and anything that depends on it.

ie.  
**old** api containing functions:
```
(projects={}, environments={}, flags={}, users={}, user settings={}, audit log={}, webhooks={}, root={})
```

**new** api containing functions
```
(Projects={}, Environments={}, Feature flags={}, Users={}, User settings={}, Audit log={}, Webhooks={}, Custom roles={}, Team members={}, Root={})
```

for example this call using the generated client no longer works because the 'flags' api no longer exists.
```
this.apiClient.apis.flags.getFeatureFlags({ projectKey: projectKey });
```

refer: https://github.com/wyvern8/launchdarkly-nodeutils which works with the copy taken from published url, but not the swagger generated from this repo. (update: repo is updated to match new structures)

here are the notes as to how the api is generated
https://github.com/swagger-api/swagger-js#tags-interface

**Comment by wyvern8** [comment]
Fyi @levlaz @Neko-Design I have updated the nodeutils to match the new structures for now, but it would be great to see some stability.

**Comment by brooswit** [comment]
Thanks for letting us know about this. We identified the issue that caused that deployment to fail and have fixed it. We are also implementing additional tests to ensure this doesn't happen in the future.

**Comment by mlafeldt** [comment]
Hey guys, looks like https://github.com/launchdarkly/ld-openapi/tree/gh-pages hasn't been updated for 6 months, so the published spec is quite old. Another problem with the CI?

**Comment by mlafeldt** [comment]
I can see that https://circleci.com/gh/launchdarkly/ld-openapi/28 has failed due to some libcurl issue.

**Comment by ashanbrown** [comment]
@wyvern8 @mlafeldt Automated CI builds should be functioning again.  The latest spec can be found at https://launchdarkly.github.io/ld-openapi/ (spec is at https://launchdarkly.github.io/ld-openapi/openapi.json) and also in the releases section of this repo at https://github.com/launchdarkly/ld-openapi/releases.  Our plan is to add more automated testing of the generated libraries in addition to automated publishing to more package repositories.  Please do let us know again if you find anything out of date.
