### ISSUE TITLE
$ref expansion for non-object types

### ISSUE THREAD

**Issue by drichelson** [launchdarkly/ld-openapi#20]
It looks like the problem solved by [this script](https://github.com/launchdarkly/ld-openapi/blob/636cb4216885aed71752f4342f789a48ed311089/scripts/expand-simple-type-refs.sh) exists elsewhere. An example is `#/definitions/CustomRoleKeyOrId` 

I did some research and it looks like there is no real workaround for v2 of Swagger/OpenAPI. v3 has been released, but there is no built-in generator for many of the platforms this repo is configured to use.

For now I propose expanding all the `$ref`s instead of adding more to the script.

**Comment by ashanbrown** [comment]
Could you tell us more about the goal of this change?  Do you know which languages are affected by this problem?

**Comment by drichelson** [comment]
@ashanbrown sure thing.
I've been working in golang and here is an example of what happens when a $ref to a string gets expanded.

Expected: 
[ldapi.CustomRoleBody](https://github.com/launchdarkly/api-client-go/blob/master/model_custom_role_body.go#L18)'s `Key` field should be a `string` or a type alias to a `string`

Actual:
The type is actually a *CustomRoleKeyOrId which is [just an empty struct](https://github.com/launchdarkly/api-client-go/blob/master/model_custom_role_key_or_id.go).

After the changes in this PR the Key field is now a string. My understanding of the v2 Swagger parser is that it doesn't properly handle primitive types.

**Comment by drichelson** [comment]
@ashanbrown any further thoughts on this?
