### ISSUE TITLE
Default environments make life difficult for API consumers

### ISSUE THREAD

**Issue by mlafeldt** [launchdarkly/ld-openapi#7]
Hey,

Thanks for the excellent OpenAPI specification. I've successfully used it to generate a [Go client library](https://github.com/mlafeldt/go-launchdarkly), and it's been working great overall! 👍

I've been using the Go library as part of my brand-new **Terraform provider for LaunchDarkly**:

https://github.com/mlafeldt/terraform-provider-launchdarkly

At this moment, the provider allows to manage LaunchDarkly projects, environments, and feature flags. While it works great in general, there are at least two [known issues](https://github.com/mlafeldt/terraform-provider-launchdarkly#known-issues) that make development of a proper provider kind of difficult:

1. Creating a new project via the LaunchDarkly API will, unfortunately, also create two environments by default (Production and Test). It's not possible to delete both since at least one must exist. The `launchdarkly_project` and `launchdarkly_environment` resources don't handle this case in a good way yet. As a workaround, it's possible to import these special environments via `terraform import`.
2. Even if we could solve the previous issue, there would still be the problem that there must be at least one project, making it impossible to have a clean slate using Terraform.

I hope you can see how providing API endpoints for creating projects _and_ environments, with the former interfering with the latter, can cause the mentioned problems for API consumers. As far as I can see, there's no way to change this surprising behavior. Please advise.

**Comment by jkodumal** [comment]
Hey @mlafeldt -- this is awesome! Right now there are a few internal invariants that would be violated if you created a project with no environments. We're going to investigate and see what the implications of removing that invariant are. I suspect we'll run into a few issues, but if we don't, we could potentially add a query param to the API to create projects with no environments.

No timeline just yet, but I'll follow up on this ticket once we try it out.

**Comment by mlafeldt** [comment]
Great! Adding a query parameter sounds like a good idea. 👍

**Comment by jkodumal** [comment]
Hey @mlafeldt -- we took a stab at this, but there are many spots where we require at least one project in the account / one environment in the project. I still do think it's a great idea that we want to tackle, but this unfortunately won't be a quick fix.

**Comment by mlafeldt** [comment]
@jkodumal I see. What about giving people the ability to choose what environment(s) to create when creating a new project via the API? At the moment, I believe it's always Production and Test. I don't see why this shouldn't be configurable (as long as there's at least one environment present). What do you think?

**Comment by jkodumal** [comment]
@mlafeldt Sorry for the slow response-- that sounds like a very good compromise. We'll spike a change to our API to allow this.

**Comment by jkodumal** [comment]
Hey @mlafeldt-- we have a spike of this working. It's not live on prod yet, but it lets you do the following when creating a new project:

```
{
	"key":"new-proj",
	"name":"New Project",
	"environments": [
		{
			"name": "Pre-production",
			"key": "pre-prod",
			"color": "C8C8C8"
		}
	]
}
``` 
When you specify the environments in the project POST, the default environments (Production and Test) will not be created-- you'll only get the environments specified in the POST body. Will this work for you? If so, we'll push this over the line and update and release our OpenAPI specification.

**Comment by mlafeldt** [comment]
@jkodumal Sounds good! I think this will allow me to address some shortcomings in the Terraform provider. Please go ahead and release the change.

**Comment by mlafeldt** [comment]
Of course, it would be nice if the new environment block would support the same fields as https://apidocs.launchdarkly.com/docs/create-environment, e.g. `defaultTtl`.

**Comment by jkodumal** [comment]
@mlafeldt Yes, it does! It's the exact same object model that you can embed in the array. I'm hoping to ship this as part of our Moonshots hackathon tomorrow.

**Comment by jkodumal** [comment]
Hey @mlafeldt -- Sorry for the lack of comms here. We did ship this improvement to the API. There's a reference to a commit above where @ashanbrown pushed the new query parameters to the OpenAPI client. Hope this helps.
